# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  lsb2-chat:
    labels:
      lsb2.template.description: "Chat Server for local environment"
      lsb2.chat.version: $TAG
    image: jghamburg/lsb2-chat:$TAG
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-chat.jar
    ports:
      - "9999:8080" # web port
      # - "49999:49999"
    environment:
      PROFILE: "default"
      PORT: 8080
      DEBUG_PORT: "49999"
#      JAVA_REMOTE_DEBUGGING: "false"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true

