# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-chat-server:
    labels:
      lsb2.template.description: "Chat Server for local environment"
      lsb2.chat.version: "local"
    image: "jghamburg/lsb2-chat:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-chat.jar
    ports:
      - "9999:9999" # web port
      - "49999:49999"
    environment:
      PROFILE: "local"
      JAVA_REMOTE_DEBUGGING: "true"
      DEBUG_PORT: "49999"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true

