# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-chat-server:
    labels:
      de.otto.template.description: "Chat Server for local environment"
      de.otto.drop.brandshopupdater.version: "local"
    image: "chat-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9999:9999" # web port
      - "49999:49999"
    environment:
      PROFILE: "local"
      JAVA_REMOTE_DEBUGGING: "true"
      DEBUG_PORT: "49999"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true

